// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import ()

type Attraction struct {
	AttractionID int64
	Title        string
	Content      string
}

type Facility struct {
	FacilityID int64
	Title      string
	Content    string
}

type LearningContent struct {
	LearningContentID  int64
	Name               string
	Description        string
	Habitat            string
	Diet               string
	ConservationStatus string
}

type Session struct {
	Token  string
	Data   []byte
	Expiry float64
}

type Ticket struct {
	TicketID   int64
	UserID     int64
	TicketUuid string
	Secret     string
	Expiry     float64
}

type User struct {
	UserID    int64
	FirstName string
	LastName  string
	Email     string
	Password  string
}
